services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/admin/Jellyfin/Config:/config
      - /home/admin/Jellyfin/Cache:/cache
      - /home/admin/Media/Media:/data

    ports:
      - 8096:8096
    restart: unless-stopped