services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/admin/nextcloud/config:/config
      - /home/admin/nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped