services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: always
    container_name: "redlib"
    ports:
      - 8080:8080 # Specify `127.0.0.1:8080:8080` instead if using a reverse proxy